### ISSUE TITLE
Mistranslation

### ISSUE THREAD

**Issue by Michael5564445** [unraid/lang-uk_UA#88]
https://github.com/unraid/lang-uk_UA/blob/4c99a0e0e7c0e296691d9917b7a844f90e280663/CA%20Auto%20Update/autoupdateapps.txt#L13

Minute=Хвилина
![IMG_20240421_200858](https://github.com/unraid/lang-uk_UA/assets/133502714/90bb1b03-5126-49f4-bca0-a71454f18d64)

**Comment by Alex2581** [comment]
Доброго дня
Поправив, Дякую. 

Good day
Corrected, thanks.

**Comment by Michael5564445** [comment]
close
